const icons = [
  {
    title: 'Common', // 常用 icon
    list: [
      'loading',
    ],
  },
  {
    title: 'Suggested', // 交互
    list: [
      // 疑问
      'question',
      'question-circle',
      'question-circle-o',
      // 暂停
      'pause',
      'pause-circle',
      'pause-circle-o',
      // info
      'info',
      'info-circle',
      'info-circle-o',
      // 感叹号 警告（三角形框）
      'warning',
      'warning-circle',
      'warning-circle-o',
      'warning-triangle',
      'warning-triangle-o',
      // 加减
      'plus',
      'plus-circle',
      'plus-circle-o',
      'plus-square',
      'plus-square-o',
      'minus',
      'minus-circle',
      'minus-circle-o',
      'minus-square',
      'minus-square-o',
      // 选择 正确 or 成功
      'check',
      'check-circle',
      'check-circle-o',
      'check-square',
      'check-square-o',
      // 关闭 错误 or 失败
      'cross',
      'cross-circle',
      'cross-circle-o',
      'cross-square',
      'cross-square-o',
      // clock
      'clock-circle',
      'clock-circle-o',
    ],
  },
  {
    title: 'application', // 应用图标
    list: [
      'abc',
      'app-store',
      'app-store-o',
      'bars',
      'book',
      'business',
      'calculator',
      'camera',
      'camera-o',
      'camera-video',
      // 图表
      'chart-area',
      'chart-bar',
      'chart-bars',
      'chart-dot',
      'chart-line',
      'chart-pie',
      'cloud',
      'cloud-o',
      'cloud-download',
      'cloud-download-o',
      'cloud-upload',
      'cloud-upload-o',
      'code-square',
      'code-square-o',
      'credit-card',
      'copy',
      'customer-service',
      'delete',
      'desktop',
      'like',
      'dislike',
      'edit',
      'ellipsis-circle',
      'ellipsis',
      'exception',
      'export',
      'export2',
      'eye-o',
      'eye',
      // 文件
      'file',
      'file-excle',
      'file-jpg',
      'file-pdf',
      'file-ppt',
      'file-text',
      'file-unknow',
      'file-word',
      'filter',
      'folder',
      'folder-open',
      'form',
      'frown',
      'frown-o',
      'hdd',
      'heart-o',
      'heart',
      'home',
      'inbox',
      'laptop',
      'link',
      'location',
      'location-o',
      'lock',
      'unlock',
      // 'login',
      'logout',
      'meh',
      'meh-o',
      'menu-fold',
      'menu-unfold',
      'message',
      'mobile',
      'notification',
      // 'oper',
      'paperclip',
      'pay-circle',
      'pay-circle-o',
      'phone',
      'picture',
      'play',
      'play-o',
      'play-circle',
      'play-circle-o',
      'power-off',
      'pushpin',
      'pushpin-o',
      'reload',
      'retweet',
      'result',
      'result-o',
      'rollback',
      'save',
      'scan',
      'search',
      'search-1',
      'setting',
      'share-alt',
      'star',
      'star-o',
      'shop-cart',
      'shrink',
      'smile',
      'smile-o',
      'solution',
      'tablet',
      'tag',
      'tags',
      'tags-o',
      'team',
      'totop',
      'user',
    ],
  },
  {
    title: 'Directional', // 方向性图标
    list: [
      'apple',
      'apple-o',
      'windows',
      'windows-o',
      'android',
      // 'android-o',
      'chrome',
      'ie',
      'github',
      'wechat',
      'alipay',
    ],
  },
  {
    title: 'Brand & Logo', // 品牌及 logo
    list: [
      'apple',
      'apple-o',
      'windows',
      'windows-o',
      'android',
      // 'android-o',
      'chrome',
      'ie',
      'github',
      'wechat',
      'alipay',
    ],
  },
]

export default icons
